### ISSUE TITLE
PHP 7.1 support for version 1.2

### ISSUE THREAD

**Issue by igrybkov** [colinmollenhour/php-redis-session-abstract#11]
Hi,

The version 1.3 contains backward incompatible change (a new method has been added to the interface [Cm\RedisSession\Handler\ConfigInterface](https://github.com/colinmollenhour/php-redis-session-abstract/commit/4b6586ed857b11efc041a594074ea38d649e7fff#diff-59dd175b9edb7e1183d5f79572950fc2).
It is the undesirable side effect when we only want to make our code compatible with PHP 7.1.

I've checked the code for the version 1.2 and didn't find any incompatibility, so the only thing which is required to make it works with PHP 7.1 is to add this version as supported into composer.json.

But, as there is no branch for that specific version, I cannot send you a pull request with a fix.

Can you please make a new release v1.2.1 with added PHP 7.1 support in the composer.json?

**Comment by colinmollenhour** [comment]
Are all your needs met now?

**Comment by igrybkov** [comment]
Yes, that's great. Thank you, @colinmollenhour
