### ISSUE TITLE
Tag to 1.8.2

### ISSUE THREAD

**Issue by R-to-the-K** [colinmollenhour/php-redis-session-abstract#14]
Colin-

With your recent update to Cm_RedisSession, you listed this module as a requirement >= 1.8.2, however its only tagged up through 1.3.2. 

Do you have to retag this module?

**Comment by colinmollenhour** [comment]
Oops.. I meant to update the Credis dependency, not the php-redis-session-abstract dependency.. Fixed and tagged a new release of Cm_RedisSession. A new release of this library is not needed. Thanks for the heads-up!
