### ISSUE TITLE
Credis (https://github.com/colinmollenhour/credis) Release 1.9.0

### ISSUE THREAD

**Issue by tkd-hgoertz** [colinmollenhour/php-redis-session-abstract#15]
PHP Notice for undefinded Index with Credis Release 1.9.0 (https://github.com/colinmollenhour/credis/releases/tag/1.9.0)

response from client is now a key/value array instead of values only

https://github.com/colinmollenhour/php-redis-session-abstract/blob/7e961834e1373058213765e7a3e391184282d863/src/Cm/RedisSession/Handler.php#L548

**Comment by Xon** [comment]
Please try the PR https://github.com/colinmollenhour/php-redis-session-abstract/pull/16

**Comment by colinmollenhour** [comment]
Oops, I suppose the old composer.json should have been more specific like "~1.8.0".

**Comment by colinmollenhour** [comment]
I actually changed this to make it compatible with old and new versions to better avoid compatibility issues.

**Comment by tkd-hgoertz** [comment]
wonderful, any release plans?

**Comment by colinmollenhour** [comment]
I just tagged v1.3.5

**Comment by huguesalary** [comment]
I just ran into this issue, it took me a while to figure it out and was breaking my code. Would you mind releasing a new version to packagist? (`1.9.1` maybe?)

**Comment by colinmollenhour** [comment]
@huguesalary I'm not following you... What would that do? The only difference between master and 1.9.0 is the Travis CI file.

**Comment by huguesalary** [comment]
You're right. I was confused. I'm using `Cm_RedisSession` but I forgot that, for some reasons (irrelevant to this thread), I'm not installing `Cm_RedisSession` via Composer. I ended up with a `colinmollenhour/credis 1.9.0`, updated via Composer, while `Cm_RedisSession` didn't get updated.
