### ISSUE TITLE
PHP 7.2 Support

### ISSUE THREAD

**Issue by buskamuza** [colinmollenhour/php-redis-session-abstract#22]
Can PHP 7.2 support be added?
It doesn't look like the code is incompatible with PHP 7.2.

**Comment by dmitry-fedyuk** [comment]
It is my PHP 7.2 compatible fork: https://github.com/mage2pro/php-redis-session-abstract

**Comment by colinmollenhour** [comment]
I updated composer.json to include PHP 7.2

**Comment by buskamuza** [comment]
Thanks!
@colinmollenhour , when do you plan to publish a new release, so we could specify it in the dependencies list?

**Comment by colinmollenhour** [comment]
Just published 1.3.8.
