### ISSUE TITLE
PHP 7.3 Support

### ISSUE THREAD

**Issue by pmclain** [colinmollenhour/php-redis-session-abstract#26]
Can PHP 7.3 support be added?
It doesn't look like the code is incompatible with PHP 7.3.

**Comment by colinmollenhour** [comment]
Yes, I believe there are no PHP 7.3 issues, but I have not tested it myself.

**Comment by ITspirit** [comment]
Why you dont write (in composer.json):

```javascript
"php": "^5.5 || ^7.0",
```
Would be easier to maitain ;-)

And Please - can you tag the last version? You´ve merged the PR, but on packagist the latest version is 1.4.0 (without PHP7.3 "support")

**Comment by colinmollenhour** [comment]
Updated and tagged. Thanks!

**Comment by ITspirit** [comment]
Thanks a lot!

Any idea why Tag 1.4.1 is still not visible on packagist? Mayber there is a connection broken in your github repo?

**Comment by colinmollenhour** [comment]
Yeah looks like the auto-update is no longer working. I just did a manual update and will see about getting auto-update fixed. Thanks for the notice.
