### ISSUE TITLE
composer credis dep

### ISSUE THREAD

**Issue by rbrown** [colinmollenhour/php-redis-session-abstract#5]
In composer.json it says `"colinmollenhour/credis":"1.6"` It the restriction on only v1.6 intentional?

**Comment by colinmollenhour** [comment]
Looks like that was just the latest at the time and was probably a defensive move against future breaking changes.. :) ~1.6 would probably be fine as I generally don't introduce bc-breaking changes but let me know what version spec you prefer or open a PR.

**Comment by rbrown** [comment]
I'd assume ~ like the rest is fine. I also realised it's requiring magneto/zendframework1. Should I have locked my Cm_RedisSession to ~1.0 if I'm using M1?

**Comment by colinmollenhour** [comment]
The colinmollenhour/Cm_RedisSession repo will always be for Magento 1. The Magento 2 crew is managing the M2 adapter themselves and both M1 and M2 adapters now use this "abstract" library.
