### ISSUE TITLE
Implement write lock instead of read lock

### ISSUE THREAD

**Issue by Yonn-Trimoreau** [colinmollenhour/php-redis-session-abstract#50]
This module does not implement write lock, but read lock instead.

The lock is currently taken when the session is first read and released when written.

You can actually prove this misconception by simply reading the first comment of the read method on this line https://github.com/colinmollenhour/php-redis-session-abstract/blob/master/src/Cm/RedisSession/Handler.php#L429

This causes bad performance on numerous Magento projects (if not all), since there are multiple HTTP requests running in parallel that need to read the session (furthermore when combining AJAX and non-AJAX requests, and especially in the checkout, or in development mode where the static file symlinking process needs to read the session).

This issue is causing more problems as the number of AJAX requests and their duration are growing.

The lock should be taken just before writing and released immediately after.

To avoid concurrency issues, a "diff" must be calculated by comparing the first session read and the session that is programmed to be written, and applied to a fresh session that is fetched just after taking the lock, then write the merged result.

I am preparing a patch to overcome this situation.

**Comment by Yonn-Trimoreau** [comment]
For those who want a cweagans/composer-patches applicable patch: [implement-write-lock-patch.txt](https://github.com/colinmollenhour/php-redis-session-abstract/files/9985299/implement-write-lock-patch.txt)

And for the Magento readers, you also must apply this patch on magento/framework module for it to work: [set-php-serialize-handler-patch.txt](https://github.com/colinmollenhour/php-redis-session-abstract/files/9985314/set-php-serialize-handler-patch.txt)

**Comment by colinmollenhour** [comment]
This is intentional because otherwise you can read stale data.. E.g. if you have an error message stored in the session it could be read by multiple requests before it is cleared rather than just one. This is the case for all phtml based frontends, as dated as they may be.

>  since there are multiple HTTP requests running in parallel

This is definitely the core of the issue.. Either there should not be parallel requests at all (not practical with modern PWAs) or the requests should all be [stateless](https://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm#sec_5_1_3) (as REST and GraphQL are intended to be). Intentionally having many session-based requests simultaneously is a big mess especially if they are writing to the session. If most are not writing anything important then those should disable locking entirely and just be read-only with no locking.

As of now in my view the session backend should provide ways to control locking as far as disabling it on a per-request basis, but I think introducing a locking mechanism that allows for non-serialized writes is not the solution to major design flaws in the upstream application.

In the case of Magento 2 I think most of the issue stems from old code that has not yet been properly refactored. For example the customer's chosen currency. This could be stored client-side and passed with each request in a header, or more simply, session locking could just be disabled entirely assuming sessions are just used to store user preferences and not used for handling error messages or form data.

**Comment by Yonn-Trimoreau** [comment]
Your module is advertised to implement write locking: reading stale data is actually the expected behavior.

Almost every software are used to read stale data on SQL based databased and NoSQL databases (that are also advertised to implement write lock).

If you need to be sure that the data is written when using a "write-lock-advertised" storage before reading it (to avoid stale data), you must wait for the previous request to end. And that is the expected and logical behavior for every frontend and backend developers.

Even the alternatives to storing sessions in Redis are write lock based, like it is the case for memcached and file storage.

With your two proposed solutions : disabling locking entirely, or flagging every "read-only" requests, the read stale data problem also arises, in exactly the same way.

But with the "disable locking entirely option" you loose locking completely and will very probably encounter random unexpected writing concurrency issues. (especially when your requests are slow and a "read in the past" session may overwrite a more fresh session completely, since writing sessions in Redis is not column or diff based but "whole session written at once" based)

And with the "flagging every request as read only", you have the burden of listing all you requests and flag them, and if you forget to do this you have random delays when concurrent requests happens... Exactly like it is the case with Magento, since it does not expose or document any way of flagging requests as read-only through your module. And that seems logical since your module is advertised to implement write locking so that should not require listing read-only requests.

You should either stop advertising you module as implementing a write lock, or propose my workflow as an option for people to choose what they really want.

**Comment by colinmollenhour** [comment]
I didn't know I was "advertising" anything.. It's not like I'm selling this code. Besides, PHP is not a transactional database, every session results in a write and this library uses locking so I called it write locking. 😆 

Your proposed strategy of waiting until the session close to merge the old data with new is perhaps clever but I don't think very good for a general purpose backend (as mentioned on the M2 issue). This library is not only used for Magento 2, but I'm not sure it is entirely safe to use with Magento 2 anyway.. Have you used this patch in production?

Anyway, couldn't this be done outside of the session backend just as well? Simply disable global locking and update `$_SESSION` before closing the session. No need to be part of the backend.

After the session is started:
```
$originalSession = $_SESSION;
// save it somewhere for later
```

Before the session is written:
```
$currentSession = $saveHandler->read(session_id());
$_SESSION = _mergeSessionData($originalSession, $currentSession, $newSession);
```

**Comment by Yonn-Trimoreau** [comment]
Sorry, I've probably used the wrong word, I'm french and I'm doing my best to reflect what I think properly. "Advertising", probably should I have used "announced to implement a write lock", or "described to". I didn't mean that you're selling it.

And I'm not asking you to change the behavior for all your users, neither making my workflow the default one for your library. You can see it like an alternative workflow.
And if you did actually change the default workflow by mine, that would probably cause problems in numerous projects that is using your library. That's not what I encourage you to do.

And yes, we could do the diff outside of your module, that's actually what I'm proposing to do in the other thread we're discussing. (and this would have the advantage of not having to serialize/unserialize the session data which I find quite dirty)

But to do things properly and be sure that we don't have concurrency issues at all, we need to follow the workflow I'm taking back from the other discussion:

1. Read session data when request starts
2. Keep a snapshot of the first read data in memory
3. Process the request
4. Calculate a diff between the first read data and what is programmed to be written
5. Take the write lock
6. Read the session data again
7. Apply the calculated diff on this fresh session data
8. Write the session
9. Release the lock

So your module should at least expose 3 public methods: `read`, `lock` and `write`, so that we can choose when we want each of this operations to happen (and do the diff between the lock and the write operations).

**Comment by Yonn-Trimoreau** [comment]
I can change my pull request to reflect this if you want. Ensuring to keep the exact same behavior by default.

**Comment by colinmollenhour** [comment]
But why not implement this in `lib/internal/Magento/Framework/Session/SessionManager.php` and pass the readOnly flag? The 9 steps you laid out have nothing to do with Redis (step 9 is implicit in step 8)

**Comment by colinmollenhour** [comment]
Sure, a separate "lock" method to use after having done a read in read-only mode would I think allow you to do it as you've outlined above. The read and write methods already exist and I don't think would need any changes.

**Comment by Yonn-Trimoreau** [comment]
Ok I will change my PR reflecting this

**Comment by colinmollenhour** [comment]
Here's another alternative that may be even easier:

```
$handler = new Handler($config, $logger, true); // read-only
session_start(); // calls $handler->read(session_id());
$handler->setReadOnly(false);
$newData = $handler->read(session_id()); // also gets lock
// update $_SESSION
session_write_close();
```

**Comment by Yonn-Trimoreau** [comment]
Nice idea! And low code, won't break anything that's for sure.
Will work on this tomorrow and ping you here.

**Comment by Yonn-Trimoreau** [comment]
@colinmollenhour here it is: https://github.com/colinmollenhour/php-redis-session-abstract/pull/52

I closed the other PR but kept it as is for history.

**Comment by Yonn-Trimoreau** [comment]
Thanks for merging the PR @colinmollenhour.

As the title of this issue is now misleading, let me break down what was agreed on for future readers.

If you want to have some sort of write locking instead of read locking, you should:
- Init the session handler with the read-only flag enabled
- Process your request
- Use the newly created `setReadOnly` method to disable read-only mode
- Optionally do some sort of diff to only apply the real modifications the request has made to the session, to the freshly read session (but do it very quick to avoid locking other processes for too long)
- Write the session

**Comment by kpitn** [comment]
Hi @Yonn-Trimoreau ,

So how do you implement this in magento ?

Thx

**Comment by Yonn-Trimoreau** [comment]
@kpitn I will do it when I find some time, probably this week-end or the next. In the meantime, the patch I've uploaded should provide a temporary solution. You can find it here: https://github.com/magento/magento2/issues/34758#issuecomment-1312524791

**Comment by Yonn-Trimoreau** [comment]
@kpitn I'm sure I already saw your name in a commit history, wasn't that on LMDW project?

**Comment by kpitn** [comment]
@Yonn-Trimoreau yes I worked on this project before (M1 & M2)

**Comment by igoragnarek** [comment]
@Yonn-Trimoreau Hello, have you used the live patch in production?
And did you manage to complete a full solution?

**Comment by Yonn-Trimoreau** [comment]
Hello @igoragnarek yes I'm currently using it in production, it does work using a patch. So I did not complete a full solution.
