### ISSUE TITLE
Minimum PHP version

### ISSUE THREAD

**Issue by adamj88** [colinmollenhour/php-redis-session-abstract#6]
Inside the README file it states:

> Requires PHP >= 5.3. Yes, this is a feature. You're welcome. ;)

However in `composer.json` the minimum PHP version is set to 5.5 here: https://github.com/colinmollenhour/php-redis-session-abstract/blob/master/composer.json#L13

Which is correct?

**Comment by colinmollenhour** [comment]
The M2 folks created the composer.json I believe, so these are probably just the M2 minimum requirements. I can't think of anything offhand that would require 5.5 or even 5.4 for M1. Give it a try and submit a PR with the appropriate version if you like. Thanks!

**Comment by colinmollenhour** [comment]
Updated README in 0959ad0feca3faf6eb70bc67e8fecb001452aedb since PHP 5.3 and 5.4 are EOL anyway. Thanks!
