### ISSUE TITLE
disabling compression

### ISSUE THREAD

**Issue by rbrown** [colinmollenhour/php-redis-session-abstract#8]
The docs in the readme for Cm_RedisSession say that to disable compression you set `compression_level` to `0`.

I don't think it's currently possible to do so, because the [constructor](https://github.com/colinmollenhour/php-redis-session-abstract/blob/master/src/Cm/RedisSession/Handler.php#L276) would set it to the default. Looking back through the history of Cm_RedisSession I think this has always been the behaviour?

[encode_data](https://github.com/colinmollenhour/php-redis-session-abstract/blob/master/src/Cm/RedisSession/Handler.php#L706) does check if the threshold is above 0, and also checks if the library is set to `none`. Setting the library to`none` does disable compression. 

I'm not sure whether you'd want the code or the docs updated? And whether this was the right repo to put the issue on?

**Comment by colinmollenhour** [comment]
Updated README. Thanks!
